import { Link } from 'react-router-dom';
import { ArrowLeft, AlertTriangle } from 'lucide-react';
import { Button } from '../components/ui/button';
import { Alert, AlertDescription } from '../components/ui/alert';

export default function Disclaimer() {
  return (
    <div className="max-w-3xl mx-auto space-y-8">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Health Disclaimer</h1>
          <p className="text-gray-600">Last updated: May 31, 2026</p>
        </div>
        <Button variant="outline" size="sm" asChild>
          <Link to="/"><ArrowLeft className="h-4 w-4 mr-2" /> Back</Link>
        </Button>
      </div>

      <Alert variant="destructive" className="border-red-300 bg-red-50">
        <AlertTriangle className="h-5 w-5 text-red-600" />
        <AlertDescription className="text-red-800 font-medium">
          This is not medical advice. Consult your healthcare provider before starting any diet.
        </AlertDescription>
      </Alert>

      <div className="prose prose-gray max-w-none space-y-6 text-gray-700">
        <h2 className="text-xl font-semibold text-gray-900">Important Health Notice</h2>
        <p>
          The information provided by KetoPlanner is for general informational and educational purposes 
          only. It is not intended to be a substitute for professional medical advice, diagnosis, or treatment.
        </p>

        <h2 className="text-xl font-semibold text-gray-900">Consult Your Doctor</h2>
        <p>
          Always seek the advice of your physician or other qualified healthcare provider with any 
          questions you may have regarding a medical condition or dietary changes. Never disregard 
          professional medical advice or delay in seeking it because of something you have read on this website.
        </p>

        <h2 className="text-xl font-semibold text-gray-900">Keto Diet Risks</h2>
        <p>The ketogenic diet may not be suitable for everyone, including individuals with:</p>
        <ul className="list-disc pl-6 space-y-1">
          <li>Type 1 diabetes or uncontrolled type 2 diabetes</li>
          <li>Kidney disease or kidney stones</li>
          <li>Pancreatitis or liver disease</li>
          <li>Gallbladder issues</li>
          <li>Eating disorders</li>
          <li>Pregnant or breastfeeding women</li>
          <li>Anyone taking medication that may be affected by dietary changes</li>
        </ul>

        <h2 className="text-xl font-semibold text-gray-900">AI-Generated Content</h2>
        <p>
          Meal plans are generated by artificial intelligence (AI) and may contain errors, inaccuracies, 
          or inappropriate suggestions. Always verify ingredients, quantities, and instructions before 
          preparing any meal. Check food labels and consult nutritional databases for accurate information.
        </p>

        <h2 className="text-xl font-semibold text-gray-900">Allergens</h2>
        <p>
          AI-generated meal plans may not account for all food allergies, intolerances, or sensitivities. 
          Always review ingredients carefully and check for potential allergens before consuming any 
          recommended meal.
        </p>

        <h2 className="text-xl font-semibold text-gray-900">No Guarantee of Results</h2>
        <p>
          KetoPlanner makes no guarantees regarding weight loss, health outcomes, or any other results 
          from following the meal plans or recommendations. Individual results vary significantly based 
          on genetics, adherence, activity level, and numerous other factors.
        </p>

        <h2 className="text-xl font-semibold text-gray-900">Assumption of Risk</h2>
        <p>
          By using KetoPlanner, you acknowledge and agree that you are assuming all risks associated 
          with following any dietary recommendations. We are not liable for any adverse effects, injuries, 
          or damages resulting from your use of the Service.
        </p>
      </div>
    </div>
  );
}
