import { Link } from 'react-router-dom';
import { ArrowLeft, FileText } from 'lucide-react';
import { Button } from '../components/ui/button';

export default function Terms() {
  return (
    <div className="max-w-3xl mx-auto space-y-8">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
          <p className="text-gray-600">Last updated: May 31, 2026</p>
        </div>
        <Button variant="outline" size="sm" asChild>
          <Link to="/"><ArrowLeft className="h-4 w-4 mr-2" /> Back</Link>
        </Button>
      </div>

      <div className="prose prose-gray max-w-none space-y-6 text-gray-700">
        <h2 className="text-xl font-semibold text-gray-900">1. Acceptance of Terms</h2>
        <p>
          By accessing or using KetoPlanner ("the Service"), you agree to be bound by these Terms of Service. 
          If you do not agree, please do not use the Service.
        </p>

        <h2 className="text-xl font-semibold text-gray-900">2. Description of Service</h2>
        <p>
          KetoPlanner provides AI-generated keto diet meal plans and nutritional calculations based on 
          user-provided information. The Service is for informational and educational purposes only.
        </p>

        <h2 className="text-xl font-semibold text-gray-900">3. Not Medical Advice</h2>
        <p>
          KetoPlanner does not provide medical advice, diagnosis, or treatment. The information provided 
          by the Service is not a substitute for professional medical advice. Always consult a qualified 
          healthcare provider before starting any diet, exercise, or nutrition program.
        </p>

        <h2 className="text-xl font-semibold text-gray-900">4. User Responsibilities</h2>
        <p>You agree to:</p>
        <ul className="list-disc pl-6 space-y-1">
          <li>Provide accurate information about yourself</li>
          <li>Not use the Service for any unlawful purpose</li>
          <li>Not attempt to reverse-engineer or abuse the AI system</li>
          <li>Consult a doctor before acting on any recommendations</li>
        </ul>

        <h2 className="text-xl font-semibold text-gray-900">5. Intellectual Property</h2>
        <p>
          The Service, including its code, design, and generated content, is protected by copyright and 
          intellectual property laws. Meal plans generated by the AI are provided for personal use only.
        </p>

        <h2 className="text-xl font-semibold text-gray-900">6. Limitation of Liability</h2>
        <p>
          KetoPlanner is provided "as is" without warranties of any kind. We are not liable for any 
          damages arising from your use of the Service, including but not limited to health issues, 
          allergic reactions, or failure to achieve weight loss goals.
        </p>

        <h2 className="text-xl font-semibold text-gray-900">7. Changes to Terms</h2>
        <p>
          We reserve the right to modify these terms at any time. Continued use of the Service after 
          changes constitutes acceptance of the new terms.
        </p>

        <h2 className="text-xl font-semibold text-gray-900">8. Contact</h2>
        <p>
          For questions about these terms, please open an issue on our GitLab repository at 
          <a href="https://gitlab.com/alaber/keto-planner" className="text-emerald-600 hover:underline ml-1">
            gitlab.com/alaber/keto-planner
          </a>.
        </p>
      </div>
    </div>
  );
}
